import React, {createContext, useState, useEffect} from 'react';
import AsyncStorage from '@react-native-community/async-storage';
// import i18n from '../utils/language';

import i18n from 'i18next';
import {useTranslation, initReactI18next} from 'react-i18next';

export const LangContext = createContext();

export const {Provider, Consumer} = LangContext;

const LangContextProvider = ({children}) => {
  const [language, setLanguage] = useState('en');
  const [pushStatus, setPushStatus] = useState(false);

  const changeLang = async (code) => {
    setLanguage(code);
    try {
      const Data = JSON.stringify(code);
      await AsyncStorage.setItem('User_Language', Data);
      console.log('ASYNC_LANG', Data);
    } catch (e) {
      console.log('Error', e);
    }
  };

  i18n
    .use(initReactI18next) // passes i18n down to react-i18next
    .init({
      resources: {
        en: {
          translation: {
            extra: {
              text_best_seller: 'Best Seller',
              text_new_arrival: 'New Arrival',
              text_added: 'Successfully Added',
              text_already: 'Item is already added to cart.',
              text_remove_cart:
                'Do you really want to remove this item from cart?',
              text_yes: 'YES',
              text_no: 'NO',
              text_company_name: 'Company name (optional)',
              text_invalid: 'Invalid Text fields!',
              text_charge:
                'You do not charge for this product and Products will be deliver in about 10 days',
              text_vat: 'Vat',
              text_week: 'Available Monday to Friday 8am - 11pm GMT',
              text_weekend: 'Saturday to Sunday 9am - 9pm GMT',
              text_all_fields: 'Fill All text fields!',
              text_field: 'Fill text field!',
              text_nomatch: 'New password does not match.',
              text_updated: 'Password is Updated.',
              text_current: 'Current Password is Invalid.',
              text_saved: 'Address is saved successfully.',
              text_already_user: 'User Already Exist! Please Login.',
              text_invalid_user: 'Invalid User/Password!',
              text_invalid_email: 'Invalid Email',
              text_sent: '  Message Sent to your Email.',
              text_no_review: 'No Reviews yet.',
            },
            common: {
              text_signin: 'Sign In',
              text_signin_mobile: 'Login with Mobile',
              text_register: 'Registration',
              text_forgot: 'Forgot Password',
              text_home: 'Home',
              text_shop: 'Shop',
              text_category: 'Categories',
              text_product: 'Products',
              text_wishList: 'WishList',
              text_cart: 'Cart',
              text_checkout_web: 'Checkout',
              text_me: 'Me',
              text_refine: 'Refine',
              text_product_description: 'Description',
              text_product_attribute: 'Additional information',
              text_product_review: 'All Reviews',
              text_product_review_form: 'Write review',
              text_me_screen: 'Menu',
              text_account: 'My account',
              text_orders: 'Orders & Returns',
              text_password: 'Change Password',
              text_address: 'Address Book',
              text_setting: 'App Settings',
              text_help_info: 'Help & Info',
              text_contact: 'Contact Us',
              text_privacy: 'Privacy',
              text_demo_config: 'Test Store',
              text_privacy_full: 'Privacy policies',
              text_about: 'About us',
              text_link_webview: 'Linking WebView',
              text_notification: 'Notification',
              text_blogs: 'Blogs',
              text_blog: 'Articles',
              text_stores: 'All vendor',
              text_new: 'NEW',
              text_sale: 'SALE',
              text_loading: 'Loading',
              text_cancel: 'Cancel',
              text_clear: 'Clear',
              text_clear_all: 'Clear all',
              text_show_all: 'Show all',
              text_apply: 'Apply',
              text_submit: 'Submit',
              text_search: 'Search',
              text_select: 'Select',
              text_add_cart: 'Add to cart',
              text_view_cart: 'View Cart',
              text_choose_item: 'Choose item',
              text_read_more: 'Read more',
              text_items: '{{count}} items',
              text_item: '{{count}} item',
              text_from: 'From',
              text_back: 'Back',
              text_next: 'Next step',
              text_edit: 'Edit',
              text_payment: 'Payment',
              text_confirm: 'Confirm',
              text_go_contact: 'Go contact',
              text_go_home: 'Go home',
              text_sale_value: 'Up To {{value}}% Off Holiday Bit',
              text_shopping_now: 'Shopping now',
              text_go_shopping: 'Go Shopping',
              text_sale_percent: 'Sale {{percent}}%',
              text_help: 'Help & Info',
              text_search_country_mobile: 'Type Here...',
              text_add: 'Add',
              text_save: 'Save',
              text_sales: 'Sales',
              text_state: 'State/Country',
              text_downloads: 'Downloads',
              text_best_seller: 'Best Seller',
              text_new_arrival: 'New Arrival',
            },
            auth: {
              text_input_password: 'Password *',
              text_input_Cpassword: 'Confirm Password *',
              text_input_field: 'Enter',
              text_input_first_name: 'First Name *',
              text_input_last_name: 'Last Name *',
              text_input_email: 'Email *',
              text_input_phone: 'Phone *',

              text_invalid_user: 'Invalid User/Password!',
              text_all_fields: 'Fill All text fields!',
              text_signin: 'Sign In',
              text_register: 'Register',
              text_register_haider: 'Sign Up',
              text_button_text: 'Sign Up',
              text_have_account: "Don't have an account?",
              text_already_account: 'Already have an account?',

              // forgot password

              text_forgot: 'Forgot Password?',
              text_forgot_haider: 'Forgot Password',
              text_invalid_email: 'Invalid Email',
              text_field: 'Fill text field!',
              text_sent: '  Message Sent to your Email.',
              text_button_forgot: 'Submit',
              text_description_forgot:
                "Enter your account email address and we'll send instructions on how to reset your password",

              // verification
              text_verify_haider: 'Verification',
              text_input_code: 'Code *',
              text_title_verify: 'Verify Your Account',
              text_button_verify: 'Verify Now',

              // number register

              text_registernum_haider: 'User Information',

              text_title_register_num: 'Give Your Personal Information',

              text_button_register: 'Click Here',
            },
            home: {
              text_me_screen_haider: 'Menu',
              text_me_screen_salesmanagment: 'Sales Management',
              text_me_screen_agenda: 'Agenda',
              text_me_screen_indicators: 'Indicators',
              text_me_screen_inventory: 'Inventory',
            },
            salemanagement: {
              text_salesmanagment_haider: 'Sales Management',
              text_button_client: 'Clients',
              text_button_performa: 'Performa',
            },
            agenda: {
              text_agenda_haider: 'Agenda',
              text_button_routes: 'Routes',
              text_button_shedule: 'Shedule',
              text_button_reshedule: 'Reshedule',
            },
            indicators: {
              text_indicators_haider: 'Indicatores',
              text_adrian_brody: 'Adrian Brody',
              text_code_indicatores: 'Code',
              text_ruc: 'RUC',
              text_tab_sales: 'Sales',
              text_tab_charges: 'Charges',
              text_active_customer: 'Active Customer',
              text_tab_creed: 'Creed',
              text_accomplished: 'Accomplished',
            },
            inventory: {
              text_inventory_haider: 'Inventory',
              text_input_search: 'Search',
            },

            drawer: {
              text_drawer_home: 'Home',
              text_drawer_sales: 'Sales',
              text_drawer_agenda: 'Agenda',
              text_drawer_indicatores: 'Indicatores',
              text_drawer_inventory: 'Inventory',
              text_drawer_setting: 'Setting',
              text_drawer_logout: 'LogOut',
            },
            setting: {
              text_setting_haider: 'App Setting',
              text_title_button_myprofile: 'My Profile',
              text_language: 'Language',
              text_language_select: 'Select',
            },
            myprofile: {
              text_myprofile_haider: 'My Profile',
              text_title_name: 'Name',
              text_title_email: 'Email',
              text_title_phone: 'Phone',
              text_title_button_changepass: 'Change Password',
              text_rbsheet_1: 'Upload Photo',
              text_rbsheet_2: 'Choose Your Profile Picture',
              text_title_button_takephoto: 'Take Photo',
              text_title_button_gallery: 'Choose From Gallery',
              text_title_button_cancel: 'Cancel',
            },
            changepassword: {
              text_changepassword_haider: 'Change Password',
              text_input_field: 'Enter',
              text_input_curpassword: 'Current Password *',
              text_input_newpassword: 'New Password *',
              text_input_Cpassword: 'Confirm Password *',
              text_title_button_savepass: 'Save New Password',
              text_description_changepassword:
                'Your New Password Must be at least 6 Characters long',

              text_current_pass_invalid: 'Current Password is Invalid.',
              text_invalid_param: 'Invalid Parameter(s)',
              text_new_pass_not: 'New password does not match.',
              text_updated: 'Updated.',
              text_try_again: 'Try again.',
            },

            clients: {
              text_clients_haider: 'Clients',
              text_input_search: 'Search',
            },

            catalog: {
              text_view_all_category: 'all >',
              text_shop_name: 'Shop {{name}}',

              text_view_all: 'View All',

              text_refine: 'Refine',

              text_description: 'Description',
              text_information: 'Additional information',
              text_reviews: 'Reviews',
              text_title_like: 'You may so like',
              text_stock: 'Instock',
              text_in_stock: '{{count}} in stock',
              text_stock_out: 'Out of stock',

              text_placeholder_search: 'Search Product',
              text_recent_search: 'Recent Searches',

              text_sort: 'Sort by',
              text_filter: 'Filter by',
              text_result: 'Show result',
              text_latest: 'Latest',
              text_sort_popular: 'Sort by popularity',
              text_sort_rating: 'Sort by average rating',
              text_sort_price_low: 'Sort by price: low to high',
              text_sort_price_high: 'Sort by price: high to low',
              text_category: 'Categories',
              text_price_range: 'Price Ranges',

              text_all_category: 'All Categories',

              text_count_review: 'base on {{count}} reviews',
              text_visit_star: '{{visit}} star',
              text_write_review: 'Write review',

              text_product_review: 'Product',

              text_tab_star: 'tab to star',
              text_review_input_text: 'Write your rating here',
              text_review_input_name: 'Name',
              text_review_input_email: 'Email',

              text_related: 'You may so like',

              text_choose_cart:
                'Please choose the quantity of items you wish to add to your cart…',

              text_store_featured: 'Features',
              text_store_visit: 'visit store',
              text_store_detail_product: 'Products',
              text_store_detail_about: 'About',
              text_store_detail_review: 'Reviews',
              text_store_detail_contact: 'Contact',
              text_store_detail_time: 'Store time',

              text_title_contact_store: 'Contact Vendor',
              text_button_contact_store: 'Send Message',
            },
            cart: {
              text_total: 'Total',
              text_subtotal: 'Subtotal',
              text_coupon: 'Coupon',
              text_coupon_input: 'Coupon code',
              text_go_checkout: 'Proceed to Checkout',
              text_delivery: 'Delivery',
              text_shipping_method: 'Shipping Method',
              text_use_billing: 'Use as billing address',
              text_use_my_address: 'Import address',
              text_payment_method: 'Payment Method',
              text_billing_address: 'Billing Address',
              text_note: 'Order notes (optional)',
              text_payment_confirm: 'Payment Confirm',
              text_payment_id: 'Your Order ID : #{{id}}',
              text_payment_message_default: 'Thank you for your order!',
              text_payment_message:
                'Click to confirm button to continue payment',
              text_payment_message_cod: 'Your order start progressing.',
              text_payment_message_bacs: 'We waiting for your payment',
              text_payment_shipping: 'Shipping {{cost}}',
              text_payment_discount: 'Discount {{cost}}',
              text_payment_tax: 'Tax {{cost}}',
              text_payment_privacy:
                'Your personal data will be used to process your order, support your experience throughout this website, and for other purposes described in our <b>privacy policy</b>.',
              text_congrats: 'Congrats !',
              text_congrats_description: 'Thanks for your purchasing.',
              text_shopping: 'Continue Shopping',
            },
            getting: {
              text_title_1: 'Shopping Smart',
              text_title_2: 'Focus UX',
              text_title_3: 'Creative Concept',
              text_subtitle_1: 'Welcome to TUGS Store',
              text_subtitle_2: 'Personalization of User Experience',
              text_subtitle_3: 'Discovering new horizons',
            },
            profile: {
              text_hello: 'Hello, {{name}}',
              text_hello_default: 'Hello, Client',
              text_signin: 'Sign In',
              text_register: 'Create Account',
              text_signout: 'Sign Out',
              text_title_logout:
                'Sign in to receive exclusive offers and\nPromotions',
              text_account: 'My Account',
              text_profile: 'My Profile',
              text_wishlist: 'WishList',
              text_title_information: 'Information',
              text_title_setting: 'Settings',
              text_setting: 'App Settings',
              text_help_info: 'Help & Info',
              text_hotline: 'Hotline',

              text_order: 'Orders & Returns',
              text_password: 'Password',
              text_address: 'Address Book',
              text_edit_account: 'Edit Account',

              text_code_order: 'Code order: {{code}}',
              text_time_order: 'Order: {{time}}',
              text_status_order: 'Status: ',

              text_input_old_pass: 'Current Password*',
              text_input_new_pass: 'New Password*',
              text_input_confirm_pass: 'Confirm Password*',
              text_password_description:
                'Your new password must be at least 6 characters long',
              text_button_password: 'Save new password',

              text_input_first_name: 'First Name *',
              text_input_last_name: 'Last Name *',
              text_input_country: 'Country / Region *',
              text_input_address_1: 'Address *',
              text_input_address_2: 'Address line 2',
              text_input_city: 'City*',
              text_input_state: 'State (optional)',
              text_input_postcode: 'Postcode',
              text_input_email: 'Email',
              text_input_phone: 'Phone',
              text_button_address: 'Save Address',

              text_language: 'Language',
              text_currency: 'Currency',
              text_config_advanced: 'Config Advanced',
              text_push_notification: 'Push notification',
              text_email_newsletter: 'Email newsletter',
              text_dark: 'Dark Theme',

              text_contact: 'Contact us',
              text_privacy: 'Privacy policies',
              text_term: 'Terms Condition',
              text_term_content: 'Term content here',
              text_about: 'About us',
              text_rate_app: 'Rate This App',

              text_name_contact: 'Contact us',

              text_description_development:
                'You can test your Store. Please input here',
              text_note_development:
                'How to get Consumer key and Consumer secret',
              text_button_development: 'Connect Store',

              text_privacy_title_1:
                '1. ABOUT THE FARFETCH GROUP AND THIS PRIVACY POLICY',
              text_privacy_description_1:
                'This Privacy Policy sets out the information that we collect, the reasons for which we collect that information, and how we can use and share that information.',
              text_privacy_title_2: '2. THIRD PARTY WEBSITES',
              text_privacy_description_2:
                'Our Website can contain links to and from the websites of our partner boutiques, advertisers, and affiliates, amongst others. If you follow a link to any of these websites, please note that this Privacy Policy does not apply to those websites. We are not responsible or liable for the privacy policies or practices of those websites, so please check their policies before you submit any personal data to those websites.',

              text_name_about: 'TUGS\nGift Shop',
              text_research: 'Research',
              text_about_description:
                'This Privacy Policy sets out the information that we collect, the reasons for which we collect that information, and how we can use and share that information.',

              text_description_edit_account:
                'This will be how your name will be displayed in the account section and in reviews.',
            },
            blog: {
              text_lastest: 'Popular',
              text_by: 'by',
              text_share: 'Share post',
            },
            inputs: {
              text_first_name: 'First Name',
              text_last_name: 'Last Name',
              text_company: 'Company name (optional)',
              text_country: 'Country',
              text_address: 'Street address',
              text_address_2: 'Apartment, suite, unit etc. (optional)',
              text_city: 'Town/City',
              text_postcode: 'Postcode',
              text_email: 'Email',
              text_phone: 'Phone *',
              text_note:
                'Notes about your order, e.g. special notes for delivery.',
              text_api: 'Domain URL',
              text_consumer_key: 'Consumer Key',
              text_consumer_secret: 'Consumer Secret',
              text_your_name: 'Your Name',
              text_your_email: 'Your Email',
              text_your_message: 'Type your message',
              text_your_title: 'Your title',
              text_your_content: 'Your content',
              text_display_name: 'Display Name',
              text_email_address: 'Email address',
            },
            empty: {
              text_title_category: 'No have any categories',
              text_subtitle_category:
                'Please contact with admin to add categories',
              text_title_product: 'No have any products',
              text_subtitle_product:
                'Please come in other category or filter value',
              text_title_product_no_category: 'No have any this category',
              text_subtitle_product_no_category:
                'Please come in other category or filter value',
              text_title_product_detail: 'Get product fail',
              text_subtitle_product_detail: 'Check id product',
              text_title_wishlist: 'Your Wishlist is empty',
              text_subtitle_wishlist:
                'Simply sign in to pick up where you left off.',
              text_title_cart: 'Your Bag is empty',
              text_subtitle_cart: 'Items added to your bag will show up here',
              text_title_order: 'You have not order yet',
              text_subtitle_order: 'Keep track of your orders and returns',
              text_title_download: 'You have not file yet',
            },
            validators: {
              text_email: 'E-Mail does not appear to be valid!',
              text_password: 'Password must be between 6 and 20 characters!',
              text_first_name:
                'First Name must be between 1 and 32 characters!',
              text_last_name: 'Last Name must be between 1 and 32 characters!',
              text_username:
                'User Name must be alpha or number and between 8 and 20 characters!',
              text_password_old: 'Password old must fill',
              text_password_confirm: 'Confirm Password must same New Password!',
              text_phone: 'Phone number does not appear to be valid!',
              text_user_email: 'Must fill value is email or username',
              text_name: 'Must fill this field!',
              text_message: 'Must fill this field!',
              text_title: 'Must fill this field!',
              text_content: 'Must fill this field!',
              text_added: 'Successfully Added',
              text_already: 'Item is already added to cart.',
            },
            notifications: {
              text_fill_value: 'Fill information fail.',
              text_create_user_success: 'You created user success.',
              text_forgot_password_success:
                'Check your email to reset password.',
              text_change_password_success: 'Password updated.',
              text_download_success: 'Download success',
              text_no_permission_write_file:
                'You do not have permission to save the file to your phone',
            },
          },
        },
        sp: {
          translation: {
            auth: {
              // login / signup
              text_input_password: 'Contraseña *',
              text_input_Cpassword: 'Confirmar contraseña *',
              text_input_field: 'Entrar',
              text_input_first_name: 'Nombre de pila *',
              text_input_last_name: 'Apellido *',
              text_input_email: 'Correo electrónico *',
              text_input_phone: 'Teléfono *',
              text_forgot: 'Se te olvidó tu contraseña?',
              text_invalid_user: 'Usuario/contraseña inválidas!',
              text_all_fields: '¡Complete todos los campos de texto!',
              text_signin: 'Registrarse',
              text_register: 'Registrarse',
              text_register_haider: 'Regístrate',
              text_button_text: 'Regístrate',
              text_have_account: '¿No tienes una cuenta?',
              text_already_account: 'Ya tienes una cuenta?',
              text_description_forgot:
                'Ingrese la dirección de correo electrónico de su cuenta y le enviaremos instrucciones sobre cómo restablecer su contraseña',

              // forgot password
              text_forgot: 'Se te olvidó tu contraseña?',
              text_forgot_haider: 'Se te olvidó tu contraseña',
              text_invalid_email: 'Email inválido',
              text_field: 'Llenar campo de texto!',
              text_sent: 'Mensaje enviado a su correo electrónico.',
              text_button_forgot: 'Enviar',
              text_description_forgot:
                'Ingrese la dirección de correo electrónico de su cuenta y le enviaremos instrucciones sobre cómo restablecer su contraseña',

              // verification

              text_verify_haider: 'Verificación',
              text_input_code: 'Código *',
              text_title_verify: 'Verifica tu cuenta',
              text_button_verify: 'verifica ahora',

              // Register number

              text_registernum_haider: 'informacion del usuario',

              text_title_register_num: 'Proporcione su información personal',

              text_button_register: 'Haga clic aquí',
            },
            home: {
              text_me_screen_haider: 'Menú',
              text_me_screen_salesmanagment: 'Gestión de ventas',
              text_me_screen_agenda: 'Agenda',
              text_me_screen_indicators: 'Indicadores',
              text_me_screen_inventory: 'Inventario',
            },
            salemanagement: {
              text_salesmanagment_haider: 'Gestión de ventas',
              text_button_client: 'Clientas',
              text_button_performa: 'Performa',
            },
            agenda: {
              text_agenda_haider: 'Agenda',
              text_button_routes: 'Rutas',
              text_button_shedule: 'Calendario',
              text_button_reshedule: 'ReCalendario',
            },
            indicators: {
              text_indicators_haider: 'Indicadores',
              text_adrian_brody: 'Adrian Brody',
              text_code_indicatores: 'Código',
              text_ruc: 'RUC',
              text_tab_sales: 'Ventas',
              text_tab_charges: 'Cargos',
              text_active_customer: 'Cliente activo',
              text_tab_creed: 'Credo',
              text_accomplished: 'Consumado',
            },
            inventory: {
              text_inventory_haider: 'Inventario',
              text_input_search: 'Buscar',
            },
            drawer: {
              text_drawer_home: 'Hogar',
              text_drawer_sales: 'Ventas',
              text_drawer_agenda: 'Agenda',
              text_drawer_indicatores: 'Indicadores',
              text_drawer_inventory: 'Inventario',
              text_drawer_setting: 'Ajuste',
              text_drawer_logout: 'Cerrar sesión',
            },
            setting: {
              text_setting_haider: 'Configuración de la aplicación',
              text_title_button_myprofile: 'Mi perfil',
              text_language: 'Idioma',
              text_language_select: 'Seleccione',
            },
            myprofile: {
              text_myprofile_haider: 'Mi perfil',
              text_title_name: 'Nombre',
              text_title_email: 'Correo electrónico',
              text_title_phone: 'Teléfono',
              text_title_button_changepass: 'Cambia la contraseña',
              text_rbsheet_1: 'subir foto',
              text_rbsheet_2: 'Elige tu foto de perfil',
              text_title_button_takephoto: 'Tomar foto',
              text_title_button_gallery: 'Elegir de la galería',
              text_title_button_cancel: 'Cancelar',
            },
            changepassword: {
              text_changepassword_haider: 'Cambia la contraseña',
              text_input_field: 'Entrar',
              text_input_curpassword: 'contraseña actual *',
              text_input_newpassword: 'Nueva contraseña *',
              text_input_Cpassword: 'Confirmar contraseña *',
              text_title_button_savepass: 'Guardar nueva contraseña',
              text_description_changepassword:
                'Su nueva contraseña debe tener al menos 6 caracteres',

              text_current_pass_invalid: 'La contraseña actual no es válida.',
              text_invalid_param: 'Parámetros inválidos',
              text_new_pass_not: 'La nueva contraseña no coincide.',
              text_updated: 'Actualizado.',
              text_try_again: 'Inténtalo de nuevo.',
            },
            clients: {
              text_clients_haider: 'Clientas',
              text_input_search: 'Buscar',
            },
          },
        },
        fr: {
          translation: {
            extra: {
              text_best_seller: 'Best-seller',
              text_new_arrival: 'Nouvelle arrivee',
              text_added: 'ajouté avec succès',
              text_already: "L'article est déjà ajouté au panier.",
              text_remove_cart:
                'Voulez-vous vraiment retirer cet article du panier?',
              text_yes: 'OUI',
              text_no: 'NON',
              text_company_name: "Nom de l'entreprise (facultatif)",
              text_invalid: 'Champs de texte non valides!',
              text_charge:
                'Vous ne facturez pas ce produit et les produits seront livrés dans environ 10 jours',
              text_vat: 'T.V.A',
              text_week: 'Disponible du lundi au vendredi de 8h à 23h GMT',
              text_weekend: 'Du samedi au dimanche de 9h à 21h GMT',
              text_all_fields: 'Remplissez tous les champs de texte!',
              text_field: 'Remplissez le champ de texte!',
              text_nomatch: 'Le nouveau mot de passe ne correspond pas.',
              text_updated: 'Le mot de passe est mis à jour.',
              text_current: 'Le mot de passe actuel est invalide.',
              text_saved: "L'adresse est enregistrée avec succès.",
              text_already_user:
                "L'utilisateur existe déjà! Veuillez vous connecter.",
              text_invalid_user: 'Utilisateur / mot de passe invalide!',
              text_invalid_email: 'Email invalide',
              text_sent: '  Message envoyé à votre e-mail.',
              text_no_review: "Pas encore d'avis.",
            },
            common: {
              text_signin: 'Se connecter',
              text_signin_mobile: 'Connectez-vous avec mobile',
              text_register: 'enregistrement',
              text_forgot: 'Mot de passe oublié',
              text_home: 'Accueil',
              text_shop: 'Boutique',
              text_category: 'Catégories',
              text_product: 'Des produits',
              text_wishList: 'Liste de souhaits',
              text_cart: 'Chariot',
              text_checkout_web: 'check-out',
              text_me: 'moi',
              text_refine: 'Affiner',
              text_product_description: 'La description',
              text_product_attribute: 'Information additionnelle',
              text_product_review: 'Tous les avis',
              text_product_review_form: 'Ecrire une critique',
              text_me: 'moi',
              text_me_screen: 'Menu',
              text_account: 'Mon compte',
              text_orders: 'Commandes et retours',
              text_password: 'Changer le mot de passe',
              text_address: "Carnet d'adresses",
              text_setting: "Paramètres de l'application",
              text_help_info: 'Aide et info',
              text_contact: 'Nous contacter',
              text_privacy: 'Intimité',
              text_demo_config: 'Magasin de test',
              text_privacy_full: 'Les politiques de confidentialité',
              text_about: 'À propos de nous',
              text_link_webview: 'Lier WebView',
              text_notification: 'Notification',
              text_blogs: 'Blogs',
              text_blog: 'Des articles',
              text_stores: 'Tous les fournisseurs',
              text_new: 'NOUVELLE',
              text_sale: 'VENTE',
              text_loading: 'Chargement',
              text_cancel: 'Annuler',
              text_clear: 'Claire',
              text_clear_all: 'Tout effacer',
              text_show_all: 'Afficher tout',
              text_apply: 'Appliquer',
              text_submit: 'Soumettre',
              text_search: 'Chercher',
              text_select: 'Sélectionner',
              text_add_cart: 'Ajouter au chariot',
              text_view_cart: 'Voir le panier',
              text_choose_item: 'Choisissez un article',
              text_read_more: 'Lire la suite',
              text_items: '{{count}} éléments',
              text_item: '{{count}} élément',
              text_from: 'De',
              text_back: 'Arrière',
              text_next: "L'étape suivante",
              text_edit: 'Éditer',
              text_payment: 'Paiement',
              text_confirm: 'Confirmer',
              text_go_contact: 'Aller contact',
              text_go_home: 'Go homerentrer chez soi',
              text_sale_value:
                "Jusqu'à {{value}}% de réduction sur Holiday Bit",
              text_shopping_now: 'Acheter maintenant',
              text_go_shopping: 'Aller faire les courses',
              text_sale_percent: 'Vente {{percent}}%',
              text_help: 'Aide et informations',
              text_search_country_mobile: 'Écrivez ici...',
              text_add: 'Ajouter',
              text_save: 'sauver',
              text_sales: 'Ventes',
              text_state: 'État / Pays',
              text_downloads: 'Téléchargements',
              text_best_seller: 'Best Seller',
              text_new_arrival: 'New Arrival',
            },
            auth: {
              text_input_email_address: "Adresse email ou nom d'utilisateur *",
              text_input_password: 'Mot de passe *',
              text_input_first_name: 'Prénom *',
              text_input_last_name: 'Nom de famille *',
              text_input_user: 'User Name *',
              text_input_email: 'Email *',
              text_forgot: 'Mot de passe oublié?',
              text_register: "S'inscrire",
              text_or: 'ou',
              text_facebook: 'Connectez-vous avec Facebook',
              text_google: 'Connectez-vous avec Google',
              text_have_account: "Vous n'avez pas de compte?",
              text_agree_register:
                'Je souhaite recevoir des offres exclusives et des conseils de style par email et sms de TUGS',
              text_already_account: 'Vous avez déjà un compte?',
              text_description_forgot:
                "Saisissez l'adresse e-mail de votre compte et nous vous enverrons des instructions pour réinitialiser votre mot de passe",
              text_description_login_mobile:
                'Connectez-vous avec votre numéro de téléphone',
              text_button_login_mobile: 'Obtenir le code',
              text_title_verify: 'Vérifiez votre compte',
              text_get_back_verify: 'revenir OTP?',
              text_send_verify: 'envoie me chercher',
              text_button_verify: 'Vérifiez maintenant',
              text_fill_verify_otp: 'Veuillez valider OTP',
              text_success_verify_otp: 'vérifié!',
              text_resend_otp: 'Renvoyer le code de vérification?',
            },
            home: {
              text_getting_start: 'Commencer',
              text_loading_page: "ACHETER L'ART MODE ET DESIGN",
            },
            catalog: {
              text_view_all_category: 'toute >',
              text_shop_name: 'Nom de la boutique}}',

              text_view_all: 'Voir tout',

              text_refine: 'Affiner',

              text_description: 'La description',
              text_information: 'Information additionnelle',
              text_reviews: 'Commentaires',
              text_title_like: 'Tu pourrais tellement aimer',
              text_stock: 'En stock',
              text_in_stock: '{{count}} en stock',
              text_stock_out: 'En rupture de stock',

              text_placeholder_search: 'Rechercher un produit',
              text_recent_search: 'recherches récentes',

              text_sort: 'Trier par',
              text_filter: 'Filtrer par',
              text_result: 'Afficher le résultat',
              text_latest: 'Dernière',
              text_sort_popular: 'Trier par popularité',
              text_sort_rating: 'Trier par note moyenne',
              text_sort_price_low: 'Trier par prix: du plus bas au plus élevé',
              text_sort_price_high: 'Trier par prix: de haut en bas',
              text_category: 'Catégories',
              text_price_range: 'Fourchettes de prix',

              text_all_category: 'toutes catégories',

              text_count_review: 'basé sur {{count}} avis',
              text_visit_star: '{{visit}} étoile',
              text_write_review: 'Ecrire une critique',

              text_product_review: 'Produit',

              text_tab_star: 'onglet en étoile',
              text_review_input_text: 'Écrivez votre évaluation ici',
              text_review_input_name: 'Nom',
              text_review_input_email: 'Email',

              text_related: 'Vous pouvez tellement aimer',

              text_choose_cart:
                "Veuillez choisir la quantité d'articles que vous souhaitez ajouter à votre panier…",

              text_store_featured: 'En vedette',
              text_store_visit: 'Visiter le magasin',
              text_store_detail_product: 'Des produits',
              text_store_detail_about: 'À propos',
              text_store_detail_review: 'Commentaires',
              text_store_detail_contact: 'Contact',
              text_store_detail_time: 'Temps de stockage',

              text_title_contact_store: 'Contacter le fournisseur',
              text_button_contact_store: 'Envoyer le message',
            },
            cart: {
              text_total: 'Totale',
              text_subtotal: 'total',
              text_coupon: 'Coupon',
              text_coupon_input: 'Code de coupon',
              text_go_checkout: 'Passer à la caisse',
              text_delivery: 'Livraison',
              text_shipping_method: 'Mode de livraison',
              text_use_billing: 'Utiliser comme adresse de facturation',
              text_use_my_address: "Importer l'adresse",
              text_payment_method: 'Mode de paiement',
              text_billing_address: 'Adresse de facturation',
              text_note: 'Notes de commande (facultatif)',
              text_payment_confirm: 'Confirmer le paiement',
              text_payment_id: 'Votre numéro de commande: # {{id}}',
              text_payment_message_default:
                'Nous vous remercions de votre commande!',
              text_payment_message:
                'Cliquez pour confirmer le bouton pour continuer le paiement',
              text_payment_message_cod: 'Votre commande commence à progresser.',
              text_payment_message_bacs: 'Nous attendons votre paiement',
              text_payment_shipping: 'Frais de port}}',
              text_payment_discount: 'Remise {{cost}}',
              text_payment_tax: 'Taxe {{cost}}',
              text_payment_privacy:
                "Vos données personnelles seront utilisées pour traiter votre commande, soutenir votre expérience sur ce site Web et à d'autres fins décrites dans notre <b>politique de confidentialité</b>.",
              text_congrats: 'Félicitations !',
              text_congrats_description: 'Merci pour votre achat.',
              text_shopping: 'Continuer vos achats',
            },
            getting: {
              text_title_1: 'Shopping intelligent',
              text_title_2: 'Focus UX',
              text_title_3: 'Concept créatif',
              text_subtitle_1: 'Bienvenue dans le magasin TUGS',
              text_subtitle_2: "Personnalisation de l'expérience utilisateur",
              text_subtitle_3: 'Découvrir de nouveaux horizons',
              text_button: 'Get Started',
            },
            profile: {
              text_hello: 'Bonjour, {{name}}',
              text_hello_default: 'Bonjour, client',
              text_signin: 'Se connecter',
              text_register: 'Créer un compte',
              text_signout: 'Déconnexion',
              text_title_logout:
                'Connectez-vous pour recevoir des offres et  nPromotions exclusivess',
              text_account: 'Mon compte',
              text_profile: 'mon profil',
              text_wishlist: 'Liste de souhaits',
              text_title_information: 'Information',
              text_title_setting: 'Paramètres',
              text_setting: "Paramètres de l'application",
              text_help_info: 'Aide et info',
              text_hotline: 'Hotline',

              text_order: 'Commandes et retours',
              text_password: 'Mot de passe',
              text_address: "Carnet d'adresses",
              text_edit_account: 'Modifier le compte',

              text_code_order: 'Ordre des codes: {{code}}',
              text_time_order: 'Temps de commande}}',
              text_status_order: 'Statut:',

              text_input_old_pass: 'Mot de passe actuel*',
              text_input_new_pass: 'Nouveau mot de passe*',
              text_input_confirm_pass: 'Confirmez le mot de passe*',
              text_password_description:
                'Votre nouveau mot de passe doit comporter au moins 6 caractères',
              text_button_password: 'Enregistrer le nouveau mot de passe',

              text_input_first_name: 'Prénom *',
              text_input_last_name: 'Nom de famille *',
              text_input_country: 'Pays / Région *',
              text_input_address_1: 'Adresse 1 *',
              text_input_address_2: 'Adresse Ligne 2 *',
              text_input_city: 'Ville*',
              text_input_state: 'État (facultatif)',
              text_input_postcode: 'Code postal',
              text_input_email: 'Email',
              text_input_phone: 'Téléphone',
              text_button_address: "Enregistrer l'adresse",

              text_language: 'Langue',
              text_currency: 'Devise',
              text_config_advanced: 'Config avancé',
              text_push_notification: 'Notification push',
              text_email_newsletter: 'Courriel',
              text_dark: 'Thème sombre',

              text_contact: 'Nous contacter',
              text_privacy: 'Les politiques de confidentialité',
              text_term: 'Termes et conditions',
              text_term_content: 'Contenu du terme ici',
              text_about: 'À propos de nous',
              text_rate_app: "Évaluer l'application",

              text_name_contact: 'Nous contacter',

              text_description_development:
                'Vous pouvez tester votre boutique. Veuillez entrer ici',
              text_note_development:
                'Comment obtenir la clé du consommateur et le secret du consommateur',
              text_button_development: 'Connecter le magasin',

              text_privacy_title_1:
                '1. À PROPOS DU GROUPE FARFETCH ET DE CETTE POLITIQUE DE CONFIDENTIALITÉ',
              text_privacy_description_1:
                'Cette politique de confidentialité définit les informations que nous collectons, les raisons pour lesquelles nous collectons ces informations et la manière dont nous pouvons utiliser et partager ces informations.',
              text_privacy_title_2: '2. SITES WEB TIERS',
              text_privacy_description_2:
                "Notre site Web peut contenir des liens vers et depuis les sites Web de nos boutiques partenaires, annonceurs et affiliés, entre autres. Si vous suivez un lien vers l'un de ces sites Web, veuillez noter que cette politique de confidentialité ne s'applique pas à ces sites Web. Nous ne sommes pas responsables des politiques ou pratiques de confidentialité de ces sites Web, veuillez donc vérifier leurs politiques avant de soumettre des données personnelles à ces sites Web.",

              text_name_about: 'TUGS  nBoutique de cadeaux',
              text_research: 'Recherche',
              text_about_description:
                'Cette politique de confidentialité définit les informations que nous collectons, les raisons pour lesquelles nous collectons ces informations et la manière dont nous pouvons utiliser et partager ces informations.',

              text_description_edit_account:
                'Ce sera ainsi que votre nom sera affiché dans la section du compte et dans les avis.',
            },
            blog: {
              text_lastest: 'Populaire',
              text_by: 'par',
              text_share: "Partager l'article",
            },
            inputs: {
              text_first_name: 'Prénom',
              text_last_name: 'Nom de famille',
              text_company: "Nom de l'entreprise (facultatif)",
              text_country: 'Pays',
              text_address: 'adresse de rue',
              text_address_2: 'Appartement, suite, unité etc. (facultatif)',
              text_city: 'Ville / Ville',
              text_postcode: 'Code postal',
              text_email: 'Email',
              text_phone: 'Téléphone',
              text_note:
                'Remarques sur votre commande, par exemple notes spéciales pour la livraison.',
              text_api: 'URL du domaine',
              text_consumer_key: 'La clé du consommateur',
              text_consumer_secret: 'Secret du consommateur',
              text_your_name: 'votre nom',
              text_your_email: 'Votre e-mail',
              text_your_message: 'Tapez votre message',
              text_your_title: 'Votre titre',
              text_your_content: 'Votre contenu',
              text_display_name: 'Afficher un nom',
              text_email_address: 'Adresse e-mail',
            },
            empty: {
              text_title_category: 'Pas de catégories',
              text_subtitle_category:
                "Veuillez contacter l'administrateur pour ajouter des catégories",
              text_title_product: 'Pas de produits',
              text_subtitle_product:
                'Veuillez entrer dans une autre catégorie ou valeur de filtre',
              text_title_product_no_category: 'Pas de cette catégorie',
              text_subtitle_product_no_category:
                'Veuillez entrer dans une autre catégorie ou valeur de filtre',
              text_title_product_detail: 'Échec du produit',
              text_subtitle_product_detail: "Vérifier l'identifiant du produit",
              text_title_wishlist: 'Votre liste de voeux est vide',
              text_subtitle_wishlist:
                'Connectez-vous simplement pour reprendre là où vous vous étiez arrêté.',
              text_title_cart: 'Votre sac est vide',
              text_subtitle_cart:
                "Les articles ajoutés à votre panier s'afficheront ici",
              text_title_order: "Vous n'avez pas encore commandé",
              text_subtitle_order:
                'Gardez une trace de vos commandes et retours',
              text_title_download: "Vous n'avez pas encore déposé",
            },
            validators: {
              text_email: "L'e-mail ne semble pas valide!",
              text_password:
                'Le mot de passe doit comprendre entre 6 et 20 caractères!',
              text_first_name:
                'Le prénom doit comprendre entre 1 et 32 ​​caractères!',
              text_last_name:
                'Le nom de famille doit comprendre entre 1 et 32 ​​caractères!',
              text_username:
                "Le nom d'utilisateur doit être alphabétique ou numérique et entre 8 et 20 caractères!",
              text_password_old: "L'ancien mot de passe doit être rempli",
              text_password_confirm:
                'Confirmer le mot de passe doit être le même nouveau mot de passe!',
              text_phone: 'Le numéro de téléphone ne semble pas valide!',
              text_user_email:
                "La valeur doit être remplie par e-mail ou nom d'utilisateur",
              text_name: 'Doit remplir ce champ!',
              text_message: 'Doit remplir ce champ!',
              text_title: 'Doit remplir ce champ!',
              text_content: 'Doit remplir ce champ!',
              text_added: 'Successfully Added',
              text_already: 'Item is already added to cart.',
            },
            notifications: {
              text_fill_value: 'Échec du remplissage des informations.',
              text_create_user_success:
                "Vous avez créé le succès de l'utilisateur.",
              text_forgot_password_success:
                'Vérifiez votre messagerie pour réinitialiser le mot de passe.',
              text_change_password_success: 'Mot de passe mis à jour.',
              text_download_success: 'Télécharger le succès',
              text_no_permission_write_file:
                "Vous n'êtes pas autorisé à enregistrer le fichier sur votre téléphone",
            },
          },
        },
        ar: {
          translation: {
            extra: {
              text_best_seller: 'الأكثر مبيعا',
              text_new_arrival: 'قادم جديد',
              text_added: 'أضيف بنجاح',
              text_already: 'تمت إضافة العنصر بالفعل إلى سلة التسوق.',
              text_remove_cart: 'هل تريد حقًا إزالة هذا العنصر من سلة التسوق؟',
              text_yes: 'نعم',
              text_no: 'لا',
              text_company_name: 'اسم الشركة (اختياري)',
              text_invalid: 'حقول نصية غير صالحة!',
              text_charge:
                'لا تفرض رسومًا على هذا المنتج وسيتم توصيل المنتجات في غضون 10 أيام تقريبًا',
              text_vat: 'ضريبة القيمة المضافة',
              text_week:
                'متاح من الاثنين إلى الجمعة من الساعة 8 صباحًا حتى 11 مساءً بتوقيت غرينتش',
              text_weekend:
                'من السبت إلى الأحد 9 صباحًا - 9 مساءً بتوقيت غرينتش',
              text_all_fields: 'املأ جميع الحقول النصية!',
              text_field: 'ملء حقل النص!',
              text_nomatch: 'كلمة المرور الجديدة غير متطابقة.',
              text_updated: 'تم تحديث كلمة المرور.',
              text_current: 'كلمة المرور الحالية غير صحيحة.',
              text_saved: 'تم حفظ العنوان بنجاح.',
              text_already_user: 'المستخدم موجود بالفعل! الرجاء تسجيل الدخول.',
              text_invalid_user: 'مستخدم / كلمة مرور غير صالحة!',
              text_invalid_email: 'بريد إلكتروني خاطئ',
              text_sent: '  تم إرسال الرسالة إلى بريدك الإلكتروني.',
              text_no_review: 'لا توجد تعليقات حتى الآن.',
            },
            common: {
              text_signin: 'تسجيل الدخول',
              text_signin_mobile: 'تسجيل الدخول مع موبايل',
              text_register: 'التسجيل',
              text_forgot: 'هل نسيت كلمة المرور',
              text_home: 'الرئيسية',
              text_shop: 'المتجر',
              text_category: 'التصنيفات',
              text_product: 'منتجات',
              text_wishList: 'قائمة الأمنيات',
              text_cart: 'سلة التسوق',
              text_checkout_web: 'الدفع',
              text_me: 'حسابي',
              text_refine: 'صقل',
              text_product_description: 'وصف',
              text_product_attribute: 'معلومة اضافية',
              text_product_review: 'جميع المراجعات',
              text_product_review_form: 'أكتب مراجعة',
              text_me_screen: 'الحساب',
              text_account: 'حسابي',
              text_orders: 'الطلبات',
              text_password: 'تغيير كلمة المرور',
              text_address: 'دليل العناوين',
              text_setting: 'إعدادات التطبيقات',
              text_help_info: 'المساعدة والمعلومات',
              text_contact: 'اتصل بنا',
              text_privacy: 'الخصوصية',
              text_demo_config: 'متجر اختبار',
              text_privacy_full: 'سياسات الخصوصية',
              text_about: 'من نحن',
              text_link_webview: 'ربط عرض الويب',
              text_notification: 'تنبيه',
              text_blogs: 'المدونات',
              text_blog: 'مقالات',
              text_stores: 'جميع البائعين',
              text_new: 'الجديد',
              text_sale: 'مخفض',
              text_loading: 'جاري التنفيذ...',
              text_cancel: 'إلغاء',
              text_clear: 'مسح',
              text_clear_all: 'امسح الكل',
              text_show_all: 'عرض الكل',
              text_apply: 'تطبيق',
              text_submit: 'ارسال',
              text_search: 'بحث',
              text_select: 'تحديد',
              text_add_cart: 'أضف إلى السلة',
              text_view_cart: 'عرض السلة',
              text_choose_item: 'اختيار المنتج',
              text_items: '{{count}} منتجات',
              text_item: '{{count}} منتج',
              text_from: 'من عند',
              text_back: 'عودة',
              text_next: 'التالي',
              text_edit: 'تعديل',
              text_payment: 'دفع',
              text_confirm: 'تأكيد',
              text_go_home: 'اذهب للمنزل',
              text_sale_value: 'ما يصل إلى {{value}} ٪ من عطلة بت',
              text_shopping_now: 'تسوق الآن',
              text_go_shopping: 'اذهب للتسوق',
              text_sale_percent: 'بيع {{percent}}٪',
              text_help: 'المساعدة والمعلومات',
              text_search_country_mobile: 'أكتب هنا...',
              text_add: 'إضافة',
              text_save: 'حفظ',
              text_sales: 'مبيعات',
              text_state: 'ولايه دوله',
              text_downloads: 'التحميلات',
              text_best_seller: 'Best Seller',
              text_new_arrival: 'New Arrival',
            },
            auth: {
              text_input_email_address:
                'عنوان البريد الإلكتروني أو اسم المستخدم *',
              text_input_password: 'كلمه السر *',
              text_input_first_name: 'الاسم الاول *',
              text_input_last_name: 'الكنية *',
              text_input_user: 'اسم المستخدم *',
              text_input_email: 'البريد الإلكتروني *',
              text_forgot: 'هل نسيت كلمة المرور؟',
              text_register: 'تسجيل',
              text_or: 'أو',
              text_facebook: 'قم بتسجيل الدخول باستخدام الفيسبوك',
              text_google: 'الدخول مع جوجل',
              text_have_account: 'ليس لديك حساب؟',
              text_agree_register:
                'أرغب في تلقي عروض حصرية ونصائح عن طريق البريد الإلكتروني والرسائل القصيرة من OREO',
              text_already_account: 'هل لديك حساب؟',
              text_description_forgot:
                'أدخل عنوان البريد الإلكتروني لحسابك وسنرسل إرشادات حول كيفية إعادة تعيين كلمة المرور الخاصة بك',
              text_description_login_mobile: 'تسجيل الدخول باستخدام رقم هاتفك',
              text_button_login_mobile: 'الحصول على رمز',
              text_fill_verify_otp: 'يرجى التحقق من صحة OTP',
              text_success_verify_otp: 'تم التحقق!',
              text_resend_otp: 'إعادة إرسال رمز التحقق؟',
              text_title_verify: 'تحقق من حسابك',
              text_button_verify: 'تحقق الآن',
            },
            home: {
              text_getting_start: 'البدء',
              text_loading_page: 'المتجر الإلكتروني',
            },
            catalog: {
              text_view_all_category: 'الكل >',
              text_shop_name: 'تسوق {{name}}',

              text_view_all: 'عرض الكل',

              text_refine: 'صقل',

              text_description: 'وصف',
              text_information: 'معلومة اضافية',
              text_reviews: 'استعراض',
              text_title_like: 'قد تحب ذلك',
              text_stock: 'في المخزن',
              text_in_stock: '{{count}} في المخزون',
              text_stock_out: 'إنتهى من المخزن',

              text_placeholder_search: 'بحث عن المنتج',
              text_recent_search: 'عمليات البحث الأخيرة',

              text_sort: 'ترتيب حسب',
              text_filter: 'مصنف بواسطة',
              text_result: 'نتيجة العرض',
              text_latest: 'آخر',
              text_sort_popular: 'فرز حسب الشعبية',
              text_sort_rating: 'فرز حسب متوسط التقييم',
              text_sort_price_low: 'فرز حسب السعر: من الأقل إلى الأعلى',
              text_sort_price_high: 'فرز حسب السعر: من الأعلى إلى الأقل',
              text_category: 'الاقسام',
              text_price_range: 'يتراوح السعر',

              text_all_category: 'جميع الفئات',

              text_count_review: 'قاعدة على {{count}} المراجعات',
              text_visit_star: '{{visit}} نجمة',
              text_write_review: 'أكتب مراجعة',
              text_product_review: 'المنتج',

              text_tab_star: 'علامة تبويب للنجمة',
              text_review_input_text: 'اكتب تقييمك هنا',
              text_review_input_name: 'اسم',
              text_review_input_email: 'البريد الإلكتروني',

              text_related: 'قد يعجبك ذلك',

              text_choose_cart:
                'يرجى اختيار كمية العناصر التي ترغب في إضافتها إلى سلة التسوق الخاصة بك ...',

              text_store_featured: 'متميز',
              text_store_visit: 'انتقل مخزن',
              text_store_detail_product: 'منتجات',
              text_store_detail_about: 'حول',
              text_store_detail_review: 'التعليقات',
              text_store_detail_contact: 'اتصل',
              text_store_detail_time: 'وقت المتجر',

              text_title_contact_store: 'اتصل بالبائع',
              text_button_contact_store: 'إرسال رسالة',
            },
            cart: {
              text_total: 'الإجمالي',
              text_subtotal: 'الإجمالي الفرعي',
              text_coupon: 'كوبون',
              text_coupon_input: 'رمز القسيمة',
              text_go_checkout: 'إكمال الدفع',
              text_delivery: 'التوصيل',
              text_shipping_method: 'طريقة الشحن',
              text_use_billing: 'استخدام كعنوان للدفع',
              text_use_my_address: 'استيراد عنوان',
              text_payment_method: 'طريقة الدفع او السداد',
              text_billing_address: 'عنوان وصول الفواتير',
              text_note: 'ملاحظات الطلب (اختياري)',
              text_payment_confirm: 'تأكيد الدفع',
              text_payment_id: 'معرف الطلب الخاص بك: # {{id}}',
              text_payment_message_default: 'شكرا لطلبك!',
              text_payment_message: 'انقر للتأكيد زر لمواصلة الدفع',
              text_payment_message_cod: 'تقدم للدفع.',
              text_payment_message_bacs: 'نحن في انتظار الدفع الخاص بك',
              text_payment_shipping: 'الشحن {{cost}}',
              text_payment_discount: 'الخصم {{cost}}',
              text_payment_tax: 'الضريبة {{cost}}',
              text_payment_privacy:
                'سيتم استخدام بياناتك الشخصية لمعالجة طلبك ودعم تجربتك عبر هذا الموقع الإلكتروني ولأغراض أخرى موضحة في <b> سياسة الخصوصية </ b>.',
              text_congrats: 'تم استلام طلبكم بنجاح !',
              text_congrats_description: 'شكراً',
              text_shopping: 'مواصلة التسوق',
            },
            getting: {
              text_title_1: 'التسوق الذكي',
              text_title_2: 'التركيز UX',
              text_title_3: 'مفهوم الإبداعي',
              text_subtitle_1: 'مرحبًا بكم في متجر TUGS',
              text_subtitle_2: 'إضفاء الطابع الشخصي على تجربة المستخدم',
              text_subtitle_3: 'اكتشاف آفاق جديدة',
              text_button: 'Get Started',
            },
            profile: {
              text_hello: 'مرحبًا {{name}}',
              text_hello_default: 'مرحباً بعودتكم',
              text_signin: 'تسجيل الدخول',
              text_register: 'إنشاء حساب',
              text_signout: 'خروج',
              text_title_logout:
                'سجّل الدخول لتلقي العروض الحصرية و\nالعروض الترويجية',
              text_account: 'حسابي',
              text_profile: 'ملفي',
              text_wishlist: 'قائمة الأمنيات',
              text_title_information: 'معلومات',
              text_title_setting: 'الإعدادات',
              text_setting: 'الاعدادات',
              text_help_info: 'المساعدة والمعلومات',
              text_hotline: 'اتصل بنا',

              text_order: 'الطلبات',
              text_password: 'كلمة المرور',
              text_address: 'عنوان الشحن',
              text_edit_account: 'تحرير الحساب',

              text_code_order: 'ترتيب الكود: {{code}}',
              text_time_order: 'الترتيب:{{time}}',
              text_status_order: 'حالة الطلب: ',

              text_input_old_pass: 'كلمة المرور الحالية*',
              text_input_new_pass: 'كلمة المرور الجديدة*',
              text_input_confirm_pass: 'تأكيد كلمة المرور*',
              text_password_description:
                'يجب أن يكون طول كلمة المرور الجديدة 6 أحرف على الأقل',
              text_button_password: 'حفظ كلمة المرور الجديدة',

              text_input_first_name: 'الاسم الاول *',
              text_input_last_name: 'الاسم الأخير *',
              text_input_country: 'البلد / المنطقة *',
              text_input_address_1: 'العنوان السطر 1 *',
              text_input_address_2: 'العنوان السطر 2',
              text_input_city: 'المدينة*',
              text_input_state: 'الدولة',
              text_input_postcode: 'الرمز البريدي',
              text_input_email: 'البريد الإلكتروني',
              text_input_phone: 'رقم الجوال',
              text_button_address: 'حفظ العنوان',

              text_language: 'اللغات',
              text_currency: 'العملة',
              text_config_advanced: 'الاعدادات المتقدمة',
              text_push_notification: 'التنبيهات',
              text_email_newsletter: 'النشرة البريدية',
              text_dark: 'الوضع الداكن',

              text_contact: 'اتصل بنا',
              text_privacy: 'سياسات الخصوصية',
              text_term: 'اتفاقية الاستخدام',
              text_term_content: 'اتفاقية الاستخدام...',
              text_about: 'من نحن',
              text_rate_app: 'قيم هذا التطبيق',

              text_name_contact: 'اتصل بنا',

              text_privacy_title_1:
                '1. حول مجموعة FARFETCH وسياسة الخصوصية هذه',
              text_privacy_description_1:
                'تحدد سياسة الخصوصية هذه المعلومات التي نجمعها ، والأسباب التي نجمع بها هذه المعلومات ، وكيف يمكننا استخدام هذه المعلومات ومشاركتها.',
              text_privacy_title_2: '2. مواقع الأطراف الثالثة',
              text_privacy_description_2:
                'يمكن أن يحتوي موقعنا الإلكتروني على روابط من وإلى مواقع متاجرنا الشريكة والمعلنين والشركات التابعة لنا ، من بين آخرين. إذا اتبعت رابطًا لأي من هذه المواقع ، فيرجى ملاحظة أن سياسة الخصوصية هذه لا تنطبق على تلك المواقع. نحن لسنا مسؤولين أو مسؤولين عن سياسات أو ممارسات الخصوصية لتلك المواقع ، لذا يرجى مراجعة سياساتهم قبل إرسال أي بيانات شخصية إلى تلك المواقع.',

              text_name_about: 'أوريو تتفاعل الأصلية\n قالب',
              text_research: 'ابحاث',
              text_about_description:
                'تحدد سياسة الخصوصية هذه المعلومات التي نجمعها ، والأسباب التي نجمع بها هذه المعلومات ، وكيف يمكننا استخدام هذه المعلومات ومشاركتها.',

              text_description_edit_account:
                'ستكون هذه هي الطريقة التي سيتم بها عرض اسمك في قسم الحساب وفي المراجعات.',
            },
            blog: {
              text_lastest: 'أحدث هذه',
              text_by: 'بواسطة',
              text_share: 'آخر حصة',
            },
            inputs: {
              text_first_name: 'الاسم الاول',
              text_last_name: 'الاسم الأخير',
              text_company: 'الشركة (اختياري)',
              text_country: 'الدولة',
              text_address: 'عنوان الشارع',
              text_address_2: 'شقة ، جناح ، وحدة الخ (اختياري)',
              text_city: 'المدينة / المدينة',
              text_postcode: 'الرمز البريدي',
              text_email: 'البريد الإلكتروني',
              text_phone: 'الهاتف اختياري)',
              text_note:
                'ملاحظات حول طلبك ، على سبيل المثال ملاحظات خاصة للتسليم.',
              text_api: 'Api الرابط',
              text_consumer_key: 'مفتاح المستهلك',
              text_consumer_secret: 'سر المستهلك',
              text_your_name: 'اسمك',
              text_your_email: 'بريدك الالكتروني',
              text_your_message: 'اكتب رسالتك',
              text_your_title: 'لقبك',
              text_your_content: 'المحتوى الخاص بك',
              text_display_name: 'اسم العرض',
              text_email_address: 'عنوان البريد الإلكتروني',
            },
            empty: {
              text_title_category: 'لا يوجد لديك أي فئات',
              text_subtitle_category: 'يرجى الاتصال مع المشرف لإضافة فئات',
              text_title_product: 'لا يوجد لديك أي منتجات',
              text_subtitle_product: 'يرجى تأتي في فئة أخرى أو قيمة التصفية',
              text_title_product_no_category: 'ليس لديك أي هذه الفئة',
              text_subtitle_product_no_category:
                'يرجى تأتي في فئة أخرى أو قيمة التصفية',
              text_title_product_detail: 'لم يتم الحصول على معلومات المنتج',
              text_subtitle_product_detail: 'تحقق المنتج معرف',
              text_title_wishlist: 'قائمة رغباتك فارغة',
              text_subtitle_wishlist:
                'ما عليك سوى تسجيل الدخول لاستعراض قائمة أمنياتك.',
              text_title_cart: 'سلة التسوق فارغة',
              text_subtitle_cart: 'المنتجات المضافة إلى السلة سوف تظهر هنا',
              text_title_order: 'لم تطلب بعد',
              text_subtitle_order: 'طلباتي',
              text_title_download: 'You have not file yet',
            },
            validators: {
              text_email: 'البريد الإلكتروني غير صحيح!',
              text_password: 'يجب أن تكون كلمة المرور بين 6 و 20 حرفًا!',
              text_first_name: 'يجب أن يكون الاسم الأول بين 1 و 32 حرفًا!',
              text_last_name: 'يجب أن يتراوح اسم العائلة بين 1 و 32 حرفًا!',
              text_username:
                'يجب أن يكون اسم المستخدم ألفا أو رقمًا ويتراوح ما بين 8 و 20 حرفًا!',
              text_password_old: 'كلمة المرور الحالية!',
              text_password_confirm:
                'تأكيد كلمة المرور يجب أن تكون كلمة المرور جديدة!',
              text_phone: 'رقم الهاتف لا يبدو صالحًا!',
              text_user_email:
                'يجب ملء القيمة هي البريد الإلكتروني أو اسم المستخدم',
              text_name: 'يجب ملء هذا الحقل!',
              text_message: 'يجب ملء هذا الحقل!',
              text_title: 'يجب ملء هذا الحقل!',
              text_content: 'يجب ملء هذا الحقل!',
              text_added: 'Successfully Added',
              text_already: 'Item is already added to cart.',
            },
            notifications: {
              text_fill_value: 'هناك بعض المعلومات غير صحيحة',
              text_create_user_success: 'تم إنشاء الحساب بنجاح.',
              text_forgot_password_success:
                'تحقق من بريدك الإلكتروني لإعادة تعيين كلمة المرور.',
              text_change_password_success: 'تم تحديث كلمة المرور',
              text_download_success: 'نجاح التحميل',
              text_no_permission_write_file:
                'ليس لديك إذن بحفظ الملف على هاتفك',
            },
          },
        },
        ch: {
          translation: {
            extra: {
              text_best_seller: '畅销书',
              text_new_arrival: '新品到货',
              text_added: '成功添加',
              text_already: '商品已添加到购物车。',
              text_remove_cart: '您是否真的要从购物车中删除该物品？',
              text_yes: '是',
              text_no: '没有',
              text_company_name: '公司名称（可选）',
              text_invalid: '无效的文本字段！',
              text_charge: '您无需为此产品付费，产品将在10天内交付',
              text_vat: '增值税',
              text_week: '格林尼治标准时间周一至周五上午8点至晚上11点开放',
              text_weekend: '格林尼治标准时间星期六至星期日上午9点至晚上9点',
              text_all_fields: '填写所有文本字段！',
              text_field: '填写文本字段！',
              text_nomatch: '新密码不匹配。',
              text_updated: '密码已更新。',
              text_current: '当前密码无效。',
              text_saved: '地址保存成功。',
              text_already_user: '用户已存在！请登录。',
              text_invalid_user: '无效的用户名/密码！',
              text_invalid_email: '不合规电邮',
              text_sent: '  邮件已发送到您的电子邮件。',
              text_no_review: '暂无评论。',
            },
            common: {
              text_signin: '登入',
              text_signin_mobile: '用手機登錄',
              text_register: '註冊',
              text_forgot: '忘記密碼',
              text_home: '家',
              text_shop: '店',
              text_category: '分類目錄',
              text_product: '產品展示',
              text_wishList: '願望清單',
              text_cart: '大車',
              text_checkout_web: '退房',
              text_me: '我',
              text_refine: '細化',
              text_product_description: '描述',
              text_product_attribute: '附加信息',
              text_product_review: '所有評論',
              text_product_review_form: '寫評論',
              text_me_screen: '我',
              text_account: '我的帳戶',
              text_orders: '訂單與退貨',
              text_password: '更改密碼',
              text_address: '地址簿',
              text_setting: '應用程式設定',
              text_help_info: '幫助與信息',
              text_contact: '聯繫我們',
              text_privacy: '隱私',
              text_demo_config: '測試店',
              text_privacy_full: '私隱政策',
              text_about: '關於我們',
              text_link_webview: '鏈接網頁瀏覽',
              text_notification: '通知',
              text_blogs: '網誌',
              text_blog: '文章',
              text_stores: '所有廠商',
              text_new: '新',
              text_sale: '特價',
              text_loading: '載入中',
              text_cancel: '取消',
              text_clear: '明確',
              text_clear_all: '全部清除',
              text_show_all: '顯示所有',
              text_apply: '應用',
              text_submit: '提交',
              text_search: '搜索',
              text_select: '選擇',
              text_add_cart: '添加到購物車',
              text_view_cart: '查看購物車',
              text_choose_item: '選擇項目',
              text_read_more: '閱讀更多',
              text_items: '{{count}} 個項目',
              text_item: '{{count}} 項目',
              text_from: '從',
              text_back: '背部',
              text_next: '下一步',
              text_edit: '編輯',
              text_payment: '付款',
              text_confirm: '確認',
              text_go_contact: '去聯繫',
              text_go_home: '回家',
              text_sale_value: '假日位最高立減{{value}}％',
              text_shopping_now: '現在購物',
              text_go_shopping: '去逛街',
              text_sale_percent: '銷售額{{percent}}％',
              text_help: '幫助與信息',
              text_search_country_mobile: '在此輸入...',
              text_add: '加',
              text_save: '保存',
              text_sales: '營業額',
              text_state: '州/國家',
              text_downloads: '資料下載',
              text_best_seller: 'Best Seller',
              text_new_arrival: 'New Arrival',
            },
            auth: {
              text_input_email_address: '電子郵箱地址或用戶名 *',
              text_input_password: '密碼*',
              text_input_first_name: '名字 *',
              text_input_last_name: '姓 *',
              text_input_user: '用戶名 *',
              text_input_email: '電郵*',
              text_forgot: '忘記密碼？',
              text_register: '寄存器',
              text_or: '要么',
              text_facebook: '用Facebook登錄',
              text_google: '使用Google登錄',
              text_have_account: '沒有帳戶？',
              text_agree_register:
                '我想通過TUGS通過電子郵件和短信收到獨家優惠和样式建議',
              text_already_account: '已經有帳號了？',
              text_description_forgot:
                '輸入您的帳戶電子郵件地址，我們將發送有關如何重設密碼的說明',
              text_description_login_mobile: '用您的電話號碼登錄',
              text_button_login_mobile: '取得驗證碼',
              text_title_verify: '驗證您的帳戶',
              text_get_back_verify: '回來OTP？',
              text_send_verify: '給我發',
              text_button_verify: '立即驗證',
              text_fill_verify_otp: '請驗證OTP',
              text_success_verify_otp: '已驗證！',
              text_resend_otp: '重新發送驗證碼？',
            },
            home: {
              text_getting_start: '開始使用',
              text_loading_page: '商店時尚與設計藝術',
            },
            catalog: {
              text_view_all_category: '全部>',
              text_shop_name: '商店{{name}}',

              text_view_all: '查看全部',

              text_refine: '細化',

              text_description: '描述',
              text_information: '附加信息',
              text_reviews: '評論',
              text_title_like: '你可能會喜歡',
              text_stock: '有現貨',
              text_in_stock: '庫存中的{{count}}',
              text_stock_out: '缺貨',

              text_placeholder_search: '搜索商品',
              text_recent_search: '最近搜尋',

              text_sort: '排序方式',
              text_filter: '過濾',
              text_result: '顯示結果',
              text_latest: '最新',
              text_sort_popular: '按人氣排序',
              text_sort_rating: '按平均評分排序',
              text_sort_price_low: '按價格排序：從低到高',
              text_sort_price_high: '按價格排序：從高到低',
              text_category: '分類目錄',
              text_price_range: '價格範圍',

              text_all_category: '所有類別',

              text_count_review: '基於{{count}}條評論',
              text_visit_star: '{{visit}}星',
              text_write_review: '寫評論',

              text_product_review: '產品',

              text_tab_star: '跳到星號',
              text_review_input_text: '在這裡寫下您的評分',
              text_review_input_name: '名稱',
              text_review_input_email: '電子郵件',

              text_related: '你可能會喜歡',

              text_choose_cart: '請選擇要添加到購物車中的物品數量…',

              text_store_featured: '精選',
              text_store_visit: '逛商店',
              text_store_detail_product: '產品展示',
              text_store_detail_about: '關於',
              text_store_detail_review: '評論',
              text_store_detail_contact: '聯繫',
              text_store_detail_time: '儲存時間',

              text_title_contact_store: '聯繫供應商',
              text_button_contact_store: '發信息',
            },
            cart: {
              text_total: '總',
              text_subtotal: '小計',
              text_coupon: '優惠券',
              text_coupon_input: '優惠卷號碼',
              text_go_checkout: '進行結算',
              text_delivery: '交貨',
              text_shipping_method: '郵寄方式',
              text_use_billing: '用作帳單地址',
              text_use_my_address: '匯入地址',
              text_payment_method: '付款方法',
              text_billing_address: '帳單地址',
              text_note: '訂單說明（可選）',
              text_payment_confirm: '付款確認',
              text_payment_id: '您的訂單ID：＃{{id}}',
              text_payment_message_default: '謝謝您的訂單！',
              text_payment_message: '點擊確認按鈕繼續付款',
              text_payment_message_cod: '您的訂單開始處理。',
              text_payment_message_bacs: '我們等待您的付款',
              text_payment_shipping: '運輸 {{cost}}',
              text_payment_discount: '折扣 {{cost}}',
              text_payment_tax: 'Tax {{cost}}',
              text_payment_privacy:
                '您的個人數據將用於處理您的訂單，支持您在整個網站上的體驗以及用於<b>隱私權政策中所述的其他目的</b>.',
              text_congrats: '恭喜 !',
              text_congrats_description: '感謝您的購買。',
              text_shopping: '繼續購物',
            },
            getting: {
              text_title_1: '購物聰明',
              text_title_2: '關注用戶體驗',
              text_title_3: '創意概念',
              text_subtitle_1: '歡迎來到TUGS商店',
              text_subtitle_2: '用戶體驗的個性化',
              text_subtitle_3: '探索新視野',
              text_button: 'Get Started',
            },
            profile: {
              text_hello: '你好, {{name}}',
              text_hello_default: '你好, 客戶',
              text_signin: '登入',
              text_register: '創建帳號',
              text_signout: '登出',
              text_title_logout: '登錄以接收獨家優惠和 n促銷',
              text_account: '我的帳戶',
              text_profile: '我的简历',
              text_wishlist: '願望清單',
              text_title_information: '信息',
              text_title_setting: '設定值',
              text_setting: '應用程式設定',
              text_help_info: '幫助與信息',
              text_hotline: '熱線',

              text_order: '訂單與退貨',
              text_password: '密碼',
              text_address: '地址簿',
              text_edit_account: '編輯帳戶',

              text_code_order: '代碼順序: {{code}}',
              text_time_order: '訂購: {{time}}',
              text_status_order: '狀態: ',

              text_input_old_pass: '當前密碼*',
              text_input_new_pass: '新密碼*',
              text_input_confirm_pass: '確認密碼*',
              text_password_description: '您的新密碼必須至少包含6個字符',
              text_button_password: '保存新密碼',

              text_input_first_name: '名字 *',
              text_input_last_name: '姓 *',
              text_input_country: '國家/地區*',
              text_input_address_1: '地址第一行 *',
              text_input_address_2: '地址行2',
              text_input_city: '市*',
              text_input_state: '狀態（可選）',
              text_input_postcode: '郵編',
              text_input_email: '電子郵件',
              text_input_phone: '電話',
              text_button_address: '保存地址',

              text_language: '語言',
              text_currency: '貨幣',
              text_config_advanced: '配置高級',
              text_push_notification: '推送通知',
              text_email_newsletter: '電子郵件通訊',
              text_dark: '黑暗主題',

              text_contact: '聯繫我們',
              text_privacy: '私隱政策',
              text_term: '條款與協議',
              text_term_content: '術語內容在這裡',
              text_about: '關於我們',
              text_rate_app: '為這個應用軟件評分',

              text_name_contact: '聯繫我們',

              text_description_development: '您可以測試您的商店。請在這裡輸入',
              text_note_development: '如何獲取消費者密鑰和消費者秘密',
              text_button_development: '連接商店',

              text_privacy_title_1: '1. 關於遠方集團和本隱私政策',
              text_privacy_description_1:
                '本隱私政策規定了我們收集的信息，收集信息的原因以及我們如何使用和共享該信息。',
              text_privacy_title_2: '2. 第三方網站',
              text_privacy_description_2:
                '我們的網站可以包含與合作夥伴精品店，廣告商和分支機構等網站之間的鏈接。如果您訪問這些網站中的任何一個鏈接，請注意，本隱私政策不適用於這些網站。我們對這些網站的隱私政策或慣例不承擔任何責任，因此在將任何個人數據提交到這些網站之前，請檢查其政策。',

              text_name_about: 'TUGS 禮品店',
              text_research: '研究',
              text_about_description:
                '本隱私政策規定了我們收集的信息，收集信息的原因以及我們如何使用和共享該信息。',

              text_description_edit_account:
                '這就是您的姓名在帳戶部分和評論中顯示的方式。',
            },
            blog: {
              text_lastest: '流行',
              text_by: '通過',
              text_share: '分享訊息',
            },
            inputs: {
              text_first_name: '名字',
              text_last_name: '姓',
              text_company: '公司名稱（可選）',
              text_country: '國家',
              text_address: '街道地址',
              text_address_2: '公寓，套房，單元等（可選）',
              text_city: '城鎮/城市',
              text_postcode: '郵編',
              text_email: '電子郵件',
              text_phone: '電話',
              text_note: '有關您的訂單的註釋，例如交貨特別說明。',
              text_api: '網域網址',
              text_consumer_key: '消費者密鑰',
              text_consumer_secret: '消費者的秘密',
              text_your_name: '你的名字',
              text_your_email: '你的郵件',
              text_your_message: '輸入您的訊息',
              text_your_title: '你的題目',
              text_your_content: '您的內容',
              text_display_name: '顯示名稱',
              text_email_address: '電子郵件地址',
            },
            empty: {
              text_title_category: '沒有任何類別',
              text_subtitle_category: '請與管理員聯繫以添加類別',
              text_title_product: '沒有任何產品',
              text_subtitle_product: '請輸入其他類別或過濾值',
              text_title_product_no_category: '沒有這個類別',
              text_subtitle_product_no_category: '請輸入其他類別或過濾值',
              text_title_product_detail: '使產品失敗',
              text_subtitle_product_detail: '檢查ID產品',
              text_title_wishlist: '你的願望清單是空的',
              text_subtitle_wishlist: '只需登錄即可從上次中斷的地方接起。',
              text_title_cart: '你的包是空的',
              text_subtitle_cart: '添加到您包中的物品將顯示在這裡',
              text_title_order: '您尚未訂購',
              text_subtitle_order: '跟踪您的訂單和退貨',
              text_title_download: '您尚未提交',
            },
            validators: {
              text_email: '電子郵件似乎無效！',
              text_password: '密碼必須在6到20個字符之間！',
              text_first_name: '名字必須介於1到32個字符之間！',
              text_last_name: '姓氏必須在1到32個字符之間！',
              text_username:
                '用戶名必須是字母或數字，並且介於8到20個字符之間！',
              text_password_old: '舊密碼必須填寫',
              text_password_confirm: '確認密碼必須與新密碼相同！',
              text_phone: '電話號碼似乎無效！',
              text_user_email: '必須填寫的值是電子郵件或用戶名',
              text_name: '必須填寫此字段！',
              text_message: '必須填寫此字段！',
              text_title: '必須填寫此字段！',
              text_content: '必須填寫此字段！',
              text_added: 'Successfully Added',
              text_already: 'Item is already added to cart.',
            },
            notifications: {
              text_fill_value: '填充信息失敗。',
              text_create_user_success: '您創建了用戶成功。',
              text_forgot_password_success: '檢查您的電子郵件以重置密碼。',
              text_change_password_success: '密碼已更新。',
              text_download_success: '下載成功',
              text_no_permission_write_file: '您無權將文件保存到手機',
            },
          },
        },
      },
      lng: language,
      fallbackLng: 'en',

      interpolation: {
        escapeValue: false,
      },
    });

  const getLanguage = (data) => {
    const Data = JSON.parse(data);
    console.log('USER_LANGUAGE', Data);
    setLanguage(Data);
  };

  const changePush = async (code) => {
    try {
      const Data = JSON.stringify(code);
      await AsyncStorage.setItem('Push', Data);
      console.log('ASYNC_Push', Data);
    } catch (e) {
      console.log('Error', e);
    }
  };

  const getPush = (data) => {
    const Data = JSON.parse(data);
    console.log('USER_PUSH', Data);
    setPushStatus(Data);
  };

  return (
    <LangContext.Provider
      value={{
        i18n,
        changeLang,
        language,
        getLanguage,
        pushStatus,
        changePush,
        getPush,
      }}>
      {children}
    </LangContext.Provider>
  );
};

export default LangContextProvider;
